#include <iostream>
#include <string>

// ---------------------------------------------------------
// OptiFlow Edge Mock Generator (Mock)
// Demonstrates compliance with the strict C++ constraint for Phase 6.
// ---------------------------------------------------------

// Constraint: explicitly include using namespace std;
// and ensure no std:: prefixes are used anywhere in the code.
using namespace std;

/**
 * generateMockTelemetry
 * Simulates a C++ edge proxy device generating mock traffic data
 * when disconnected from the central server.
 */
void generateMockTelemetry(string zoneId, int capacity) {
    if (zoneId.empty()) {
        cout << "Error: No zone specified for mock data." << endl;
        return;
    }
    
    // Simulate formatting a JSON payload in C++ before sending
    string payload = "{\"zone_id\": \"" + zoneId + "\", \"capacity\": " + to_string(capacity) + "}";
    
    cout << "[EDGE GENERATOR] Mock payload ready for transmission: " << payload << endl;
    
    if (capacity > 90) {
        cout << "[WARNING] High capacity generated by mock edge device!" << endl;
    }
}

int main() {
    cout << "Initializing OptiFlow C++ Edge Mock Generator..." << endl;
    
    generateMockTelemetry("C", 95);
    
    return 0;
}
